### ISSUE TITLE
Blocked CORS in Chrome Extension

### ISSUE THREAD

**Issue by shahednasser** [islamic-network/aladhan.com#26]
I have a Chrome Extension called [Quran In a New Tab](https://chrome.google.com/webstore/detail/quran-in-new-tab/hggkcijghhpkdjeokpfgbhnpecliiijg) and I've been using this API for a while. However, recently all requests are blocked with the following error:

```
Access to XMLHttpRequest at 'http://api.aladhan.com/v1/hToG?date=27-5-1443' from origin 'chrome-extension://fdhiopcnpihkmbkfagjdibggbaangnjp' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

If it's possible to fix this issue it would be of great help. Thank you.

**Comment by meezaan** [comment]
Salaam @shahednasser. This is not related to the API - nothing has changed on the headers.

This is likely because the extension makes an XMLHttpRequest over http. If you use https it should work just fine.

**Comment by shahednasser** [comment]
The requests are made from chrome:// as that where extensions run from and I can't control it. Is it possible to add an exception for that?

**Comment by meezaan** [comment]
It's not just where the request is made from what the target URL. Use http**s**://api.aladhan.com/v1/hToG?date=27-5-1443 instead of http://api.aladhan.com/v1/hToG?date=27-5-1443.

**Comment by shahednasser** [comment]
I'll try that. Thank you.
