### ISSUE TITLE
Incorrect calculation post daylight savings

### ISSUE THREAD

**Issue by agmemon10** [islamic-network/aladhan.com#40]
Post daylight savings, (using the Umm ul-Qurra method) the Isha calculation after maghrib is off by 30 minutes. it used to correctly show Isha being 90 minutes after maghrib, but now it's 120 minutes after maghrib

**Comment by meezaan** [comment]
> Post daylight savings, (using the Umm ul-Qurra method) the Isha calculation after maghrib is off by 30 minutes. it used to correctly show Isha being 90 minutes after maghrib, but now it's 120 minutes after maghrib

This has nothing to do with daylight savings, but with Ramadan. The Umm al-Qura method states that in Ramadan Isha will be 120 minutes after Maghrib.
