### ISSUE TITLE
can you provide an example url with longitude latitude and year and month?

### ISSUE THREAD

**Issue by xyzbilal** [islamic-network/aladhan.com#41]
I tried many version but always get bad request. can you please provide an example url for this purpose. Best regards

**Comment by meezaan** [comment]
> I tried many version but always get bad request. can you please provide an example url for this purpose. Best regards

An example URL of what? The application or the API? The former has no yearly view.

**Comment by xyzbilal** [comment]
Im sorry for providing less information about my request. I want try  this url[https://aladhan.com/prayer-times-api]( 1. Prayer Times Calendar - http://api.aladhan.com/v1/calendar/:year/:month ) and in document it says longitude and latidute must provided. I tried many method to add lat and lng to url but always get error message.  Thanks in advance

**Comment by meezaan** [comment]
Did you no see the example request?

**Comment by xyzbilal** [comment]
Ahh. So sory to take your time. I couldnt realise there is an example request. thanks for your effort.

**Comment by meezaan** [comment]
No problem!
