### ISSUE TITLE
I'm not able to use local APIs

### ISSUE THREAD

**Issue by AdeebAldkheel** [islamic-network/aladhan.com#44]
I tried to call http://localhost:8082/v1/calendarByCity/2024/4?city=Riyadh&method=4 from my docker [ docker run -it -p 8082:8080  ghcr.io/islamic-network/aladhan.com:latest ] but I'm getting Error: **Sorry, we could not find the URL you are after**.

**Comment by meezaan** [comment]
> I tried to call http://localhost:8082/v1/calendarByCity/2024/4?city=Riyadh&method=4 from my docker [ docker run -it -p 8082:8080  ghcr.io/islamic-network/aladhan.com:latest ] but I'm getting Error: **Sorry, we could not find the URL you are after**.

You are running the app and trying to access the api. You have to use the api repo for the api.
